import type { NextPage } from "next";
import Head from "next/head";
import { ProposalList } from "../components/proposal_list";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"w-full max-w-5xl"}>
        <h1>Crowdfund $Sol</h1>
        <ProposalList />
      </main>
    </>
  );
};

export default Home;
