[programs.localnet]
program = "E7T5m2vsc2xrzjGxU4Khh2Qz2nFJHKudyvFoJM6fLjaa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/necmttn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
